const placeHolderData = [
  {
    id: 'tweet0',
    avatar: null,
    author_name: 'null',
    author_handle: 'null',
    author_id: 'null',
    date: 0,
    body: 'null',
  },
  {
    id: 'tweet1',
    avatar: null,
    author_name: 'null',
    author_handle: 'null',
    author_id: 'null',
    date: 0,
    body: 'null',
  },
  {
    id: 'tweet2',
    avatar: null,
    author_name: 'null',
    author_handle: 'null',
    author_id: 'null',
    date: 0,
    body: 'null',
  },
  {
    id: 'tweet3',
    avatar: null,
    author_name: 'null',
    author_handle: 'null',
    author_id: 'null',
    date: 0,
    body: 'null',
  },
  {
    id: 'tweet4',
    avatar: null,
    author_name: 'null',
    author_handle: 'null',
    author_id: 'null',
    date: 0,
    body: 'null',
  },
  {
    id: 'tweet5',
    avatar: null,
    author_name: 'null',
    author_handle: 'null',
    author_id: 'null',
    date: 0,
    body: 'null',
  },
  {
    id: 'tweet6',
    avatar: null,
    author_name: 'null',
    author_handle: 'null',
    author_id: 'null',
    date: 0,
    body: 'null',
  },
  {
    id: 'tweet7',
    avatar: null,
    author_name: 'null',
    author_handle: 'null',
    author_id: 'null',
    date: 0,
    body: 'null',
  },
]

export default placeHolderData
